#!/bin/bash
HOME_ROOT=~
MATLAB_ROOT=/Applications/MATLAB_R2015b.app/bin/matlab

DIR=$( cd "$( dirname "$0" )" && pwd )
cd $DIR

xterm -e ./start_recording_buffer.sh &
#$MATLAB_ROOT -nodesktop -nosplash -r "cd $DIR; start_gripforce_client()"

cd /Users/philip/tsg_code/PycharmProjects/gripforce2ft
xterm -e python gripforce2ft.py buffer://localhost:1972 /dev/cu.usbserial-AI04441H 50 True